### ISSUE TITLE
Convert project into a DLL for portability.

### ISSUE THREAD

**Issue by jselmani** [jselmani/OculusDataExtractor#2]
The project is currently a standalone console application that initializes the HMD and then grab position and orientation data.  At the moment, this works great and accomplishes exactly what it needs to, but it could be better.

As our group has already discussed, we should take the project and convert it into a DLL so it is more portable and can be used in Unity where we are creating our space flight experience.

To not complicate things, let's leave the current standalone application intact and in a separate directory as to not overwrite what is currently working.  We can name this directory `DLL`.

Happy hacking 👍

**Comment by ericschv** [comment]
I agree we should create another directory specifically for the DLL. The name `DLL` sounds like a suitable name to use.

**Comment by jselmani** [comment]
@RosarioAleCali has already opened a PR.  Do you want to pull his commit and set that up @ericschv ?

**Comment by ericschv** [comment]
@jselmani how would I go about pulling his commit in the git console?

**Comment by jselmani** [comment]
https://blog.scottlowe.org/2015/09/04/checking-out-github-pull-requests-locally/

Really good resource for that :)

**Comment by jselmani** [comment]
Although we merged @RosarioAleCali pull request, it is currently a WIP.  We are currently not able to see the `ovrTrackingState` `StatusFlags` property have a value greater than 0.

**Comment by ericschv** [comment]
@jselmani should this issue be closed and have another one opened specifically for the `ovrTackingState` and `StatusFlags` not outputting properly?

**Comment by jselmani** [comment]
@ericschv that sounds like a good idea.  I'll close this now.  Could you please open an issue regarding the incorrect output please?
